# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
commands:
  print_pipeline_id:
    parameters:
      workflow_id:
        default: "CIRCLE_WORKFLOW_ID"
        type: string
    steps:
      - run: echo "The circle ci id is <<parameters.workflow_id>>"
jobs:
  print_pipeline:
    docker:
      - image: cimg/base:2020.01
    steps:
      - print_pipeline_id:
          workflow_id: "${CIRCLE_WORKFLOW_ID}"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  pipeline-workflow:
    jobs:
      - print_pipeline